### ISSUE TITLE
"quietFixPredicate" is not defined

### ISSUE THREAD

**Issue by abbotto** [mradionov/eslint-plugin-disable#20]
In the `v1.0.2` release there is a bug in the following file:

`src/translateOptions.js`

line 28: `fix: (cliOptions.fix || cliOptions.fixDryRun) && (cliOptions.quiet ? quietFixPredicate : true),`

It cause the following error:

`[eslint-plugin-disable] ReferenceError: quietFixPredicate is not defined
    at translateOptions (/app_directory/node_modules/eslint-plugin-disable/src/translateOptions.js:28:74)
    at Object.<anonymous> (/app_directory/node_modules/eslint-plugin-disable/index.js:70:35)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Plugins.load (/app_directory/node_modules/eslint/lib/config/plugins.js:91:26)`

Adjusting line 28 to the following seems to fix the issue:

`fix: (cliOptions.fix || cliOptions.fixDryRun) && (cliOptions.quiet ? cliOptions.quietFixPredicate : true),`

**Comment by mradionov** [comment]
Thanks, I'll take a look

**Comment by mradionov** [comment]
Fix has been released in version [1.0.3](https://github.com/mradionov/eslint-plugin-disable/releases/tag/v1.0.3)
