### ISSUE TITLE
Tests failing: "No ESLint configuration found"

### ISSUE THREAD

**Issue by nwalters512** [mradionov/eslint-plugin-disable#6]
I've forked this project to add a feature I want, and I'm trying to get everything up and running. When I run `npm test`, the tests fail:

```
# index: have processors for default extensions
not ok 2 should be equivalent
  ---
    operator: deepEqual
    expected: [ '.js', '.jsx' ]
    actual:   []
    at: Test.<anonymous> (/home/nathan/git/eslint-plugin-disable/test/index.test.js:22:5)
```

Upon further debugging, things start to break at https://github.com/mradionov/eslint-plugin-disable/blob/master/index.js#L45. Although ESLint doesn't actually print an error at this line as is documented, I see the following when I log `err` to the console:

```
{ Error: No ESLint configuration found.
    at getLocalConfig (/home/nathan/git/eslint-plugin-disable/node_modules/eslint/lib/config.js:168:33)
    at Config.getConfig (/home/nathan/git/eslint-plugin-disable/node_modules/eslint/lib/config.js:263:22)
    at CLIEngine.getConfigForFile (/home/nathan/git/eslint-plugin-disable/node_modules/eslint/lib/cli-engine.js:783:29)
    at Object.<anonymous> (/home/nathan/git/eslint-plugin-disable/index.js:43:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
  messageTemplate: 'no-config-found',
  messageData: 
   { directory: '/home/nathan/git/eslint-plugin-disable',
     filesExamined: [ '/home/nathan/git/eslint-plugin-disable/package.json' ] } }
```

It looks like it expects there to actually be a config file present. However, your CI tests are running fine without one. Is there anything I have to do to get the project properly set up for development on my machine?

**Comment by mradionov** [comment]
The issue occurs with ESLint v3.0, I'll investigate, thanks!

**Comment by mradionov** [comment]
I've removed failing tests, because they were not very useful and have been very situational.
Make sure to grab the latest master branch.
I am not going to release this fix, because there is nothing new to plugin itself.
Plugin itself seems to be working fine with ESLint v3.0. Thanks!

**Comment by nwalters512** [comment]
Thanks for the quick fix!
